[colors]
# OpenCode Dark Theme for WezTerm
# Based on OpenCode 1.0.51 default theme
# https://github.com/sst/opencode

foreground = '#eeeeee'
background = '#0a0a0a'

cursor_bg = '#fab283'
cursor_fg = '#0a0a0a'
cursor_border = '#fab283'

selection_fg = '#eeeeee'
selection_bg = '#3c3c3c'

scrollbar_thumb = '#484848'
split = '#484848'

# ANSI colors
ansi = [
  '#1e1e1e', # black
  '#e06c75', # red
  '#7fd88f', # green
  '#e5c07b', # yellow
  '#5c9cf5', # blue
  '#9d7cd8', # magenta/purple
  '#56b6c2', # cyan
  '#808080', # white
]

# Bright ANSI colors
brights = [
  '#606060', # bright black
  '#e06c75', # bright red
  '#7fd88f', # bright green
  '#e5c07b', # bright yellow
  '#5c9cf5', # bright blue
  '#9d7cd8', # bright magenta/purple
  '#56b6c2', # bright cyan
  '#eeeeee', # bright white
]

[colors.tab_bar]
background = '#141414'

[colors.tab_bar.active_tab]
bg_color = '#1e1e1e'
fg_color = '#fab283'

[colors.tab_bar.inactive_tab]
bg_color = '#141414'
fg_color = '#808080'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#282828'
fg_color = '#eeeeee'

[colors.tab_bar.new_tab]
bg_color = '#141414'
fg_color = '#808080'

[colors.tab_bar.new_tab_hover]
bg_color = '#282828'
fg_color = '#fab283'

[metadata]
name = "OpenCode Dark"
author = "Based on OpenCode theme"
