# Silt Theme Colors
# Primary: #d4a574 | Secondary: #8ba0b8 | Accent: #b88fa0
# Red: #d47474 | Green: #a5b880 | Cyan: #80b8a5 | Yellow: #e6b886

[character]
success_symbol = "[❯](bold #d4a574)"
error_symbol = "[❯](bold #d47474)"

[directory]
read_only = " 󰌾"
style = "bold #d4a574"

[git_branch]
symbol = " "
style = "bold #8ba0b8"

[git_status]
style = "bold #e6b886"

[git_commit]
tag_symbol = '  '
style = "#b88fa0"

[cmd_duration]
style = "#9a8f84"

[aws]
symbol = " "
style = "#e6b886"

[buf]
symbol = " "
style = "#80b8a5"

[bun]
symbol = " "
style = "#d4a574"

[c]
symbol = " "
style = "#8ba0b8"

[cpp]
symbol = " "
style = "#8ba0b8"

[cmake]
symbol = " "
style = "#9a8f84"

[conda]
symbol = " "
style = "#a5b880"

[crystal]
symbol = " "
style = "#e8e3df"

[dart]
symbol = " "
style = "#80b8a5"

[deno]
symbol = " "
style = "#a5b880"

[docker_context]
symbol = " "
style = "#8ba0b8"

[elixir]
symbol = " "
style = "#b88fa0"

[elm]
symbol = " "
style = "#80b8a5"

[fennel]
symbol = " "
style = "#a5b880"

[fortran]
symbol = " "
style = "#b88fa0"

[fossil_branch]
symbol = " "
style = "#8ba0b8"

[gcloud]
symbol = " "
style = "#e6b886"

[golang]
symbol = " "
style = "#80b8a5"

[gradle]
symbol = " "
style = "#a5b880"

[guix_shell]
symbol = " "
style = "#e6b886"

[haskell]
symbol = " "
style = "#b88fa0"

[haxe]
symbol = " "
style = "#d4a574"

[hg_branch]
symbol = " "
style = "#b88fa0"

[hostname]
ssh_symbol = " "
style = "#8ba0b8"

[java]
symbol = " "
style = "#d47474"

[julia]
symbol = " "
style = "#b88fa0"

[kotlin]
symbol = " "
style = "#b88fa0"

[lua]
symbol = " "
style = "#8ba0b8"

[memory_usage]
symbol = "󰍛 "
style = "#e6b886"

[meson]
symbol = "󰔷 "
style = "#8ba0b8"

[nim]
symbol = "󰆥 "
style = "#e6b886"

[nix_shell]
symbol = " "
style = "#8ba0b8"

[nodejs]
symbol = " "
style = "#a5b880"

[ocaml]
symbol = " "
style = "#d4a574"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
style = "bold #b88fa0"

[perl]
symbol = " "
style = "#8ba0b8"

[php]
symbol = " "
style = "#b88fa0"

[pijul_channel]
symbol = " "
style = "#b88fa0"

[pixi]
symbol = "󰏗 "
style = "#80b8a5"

[python]
symbol = " "
style = "#80b8a5"

[rlang]
symbol = "󰟔 "
style = "#8ba0b8"

[ruby]
symbol = " "
style = "#d47474"

[rust]
symbol = "󱘗 "
style = "#d4a574"

[scala]
symbol = " "
style = "#d47474"

[status]
symbol = " "
style = "#d47474"

[swift]
symbol = " "
style = "#d4a574"

[xmake]
symbol = " "
style = "#d4a574"

[zig]
symbol = " "
style = "#d4a574"
